[package]
name = "technical_analysis"
version = "0.0.0"
edition = "2021"

[dependencies]
rust_decimal = { version = "1.35", features = ["maths"], optional = true }

[dev-dependencies]

[features]
default = ["precision", "simd"]
simd = []
precision = ["rust_decimal"]
unsafe = []