name: Rust CI

on:
  pull_request:
    branches:
      - release-next
    types:
      - open
      - edited
      - reopened
      - synchronize
    paths-ignore:
      - 'infrastructure/**'
      - '.github/workflows/infrastructure-cicd.yml'

env:
  CARGO_TERM_COLOR: always

jobs:
  rust-ci:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Rust Release
        uses: ./.github/actions/rust_ci
 