name: Rust CI Pipeline

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/rust-ci.yml'
    paths-ignore:
      - 'infrastructure/**'
      - '.github/workflows/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Check Style
      run: cargo clippy --verbose -- -D warnings 
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
